# Generated by Django 3.2.9 on 2021-11-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('question_text', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('categories', models.ManyToManyField(through='design_fields.QuestionDesignField', to='design_fields.DesignField')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
