# Generated by Django 3.2.9 on 2021-11-11 14:41

from django.db import migrations, models
import django.utils.timezone
import uploads.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='비밀번호')),
                ('first_name', models.CharField(max_length=30, verbose_name='이름')),
                ('last_name', models.CharField(max_length=30, verbose_name='성')),
                ('nickname', models.CharField(max_length=30, verbose_name='닉네임')),
                ('profile_image', models.ImageField(blank=True, upload_to=uploads.utils.get_uploaded_file_path)),
                ('acc_type', models.CharField(choices=[('ME', 'Mentee'), ('MO', 'Mentor')], default='ME', max_length=30, verbose_name='계정 유형')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
