# Generated by Django 3.2.9 on 2021-11-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='uploaded_audio',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='uploaded_file',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='uploaded_image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='uploaded_video',
        ),
    ]
