# Generated by Django 3.2.9 on 2021-11-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('design_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondesignfield',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
