# Generated by Django 3.2.9 on 2021-11-09 16:27

from django.db import migrations, models
import uploads.utils
import uploads.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=uploads.utils.get_uploaded_file_path, validators=[uploads.validators.validate_audio_file_extension])),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=uploads.utils.get_uploaded_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to=uploads.utils.get_uploaded_file_path)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=uploads.utils.get_uploaded_file_path, validators=[uploads.validators.validate_video_file_extension])),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
        ),
    ]
